className: AcmuaMuTrafficUnit
baseClass: TrafficUnit
tid: 480
triggers: [beforeDel, afterAdd, afterSet, recover]
attributes:
  - name: featureList
    attrId: 0
    type: FeatureList
    default: [xpic, xpic2_2, xpic7_14M, airport]
    mutable: false
children:
   - name : EthPort
     type : PhyPort
     id : 1
     count : 4
     groupType : map
     autoCreate: {"E-1": [EthPort_E_3in1, {displayName: "PROT/PLA/LMT"}], "E-2": [EthPort_E_1G, {displayName: "GbE1&PoE"}], "O-3": [EthPort_O_1G, {displayName: "GbE2"}], "AIR-0": EthPort_Air}
   - name : LogicAirPort
     type : AcmuaLogicAirPort
     id : 2
     count : 1
     autoCreate: true


