className: AcmuaWorkmode
baseClass: Workmode
tid: 242
triggers: [constraintSet, afterSet]
attributes:
  - name: bandwidth
    attrId: 0
    type: ETSI112MBandWidthEnum
    default: ETSI_7M
    mutable: true
  - name: modulation
    attrId: 1
    type: Qam2048ModulationEnum
    default: QPSK
    mutable: true
  - name: codingType
    attrId: 2
    type: CodingTypeEnum
    default: normal
    mutable: true















