className: CfmLbResult
tid: 355
triggers: [afterGet]
persistence: None
attributes:
  - name: validResult
    attrId: 0 
    type: BYTE
    minimum: 0
    maximum: 1
    default: 0
    mutable: false
  - name: sourceMPID
    attrId: 1 
    type: WORD16
    default: 0
    mutable: false
  - name: destinationMac
    attrId: 2
    type: MacAddr 
    mutable: false
  - name: sendLBNumber
    attrId: 3 
    type: WORD32
    default: 0
    mutable: false
  - name: rcvLBNumber
    attrId: 4 
    type: WORD32
    default: 0
    mutable: false  
  - name: startTime
    attrId: 5 
    type: Date
    mutable: false
  - name: endTime
    attrId: 6 
    type: Date
    mutable: false
  - name: failInfo
    attrId: 7 
    type: WORD32
    default: 0
    mutable: false
