className: CfmLmResult
tid: 356
triggers: [afterGet]
persistence: None 
attributes:
  - name: validResult
    attrId: 0 
    type: BYTE
    minimum: 0
    maximum: 1
    default: 0
    mutable: false
  - name: sourceMPID
    attrId: 1
    type: WORD16
    default: 0
    mutable: false
  - name: destMPID
    attrId: 1
    type: WORD16
    default: 0
    mutable: false
  - name: nearLastLossRate
    attrId: 3 
    type: WORD32
    default: 0
    mutable: false
  - name: nearAveLossRate
    attrId: 4
    type: WORD32
    default: 0
    mutable: false
  - name: farLastLossRate
    attrId: 5
    type: WORD32
    default: 0
    mutable: false
  - name: farAveLossRate
    attrId: 6
    type: WORD32
    default: 0
    mutable: false 
  - name: startTime
    attrId: 7
    type: Date
    mutable: false
  - name: endTime
    attrId: 8
    type: Date
    mutable: false
  - name: failInfo
    attrId: 9
    type: WORD32
    default: 0
    mutable: false

