className: DevicePara
tid: 202
triggers: [afterGet, constraintSet, recover,afterSet]
attributes:
  - name: siteId
    attrId: 0
    type: String
    maxLength: 101
    mutable: true
  - name: neId
    attrId: 1
    type: WORD32
    mutable: true
  - name: neName
    attrId: 2
    type: String
    maxLength: 31
    mutable: true
    default: "zte"
  - name: neType
    attrId: 3
    type: String
    maxLength: 10
    default: "NR8960"
    mutable: false
  - name: ip
    attrId: 4
    type: IPv4Addr
    default: "193.254.1.2"
    mutable: true
  - name: netMask
    attrId: 5
    type: IPv4Addr
    default: "255.255.255.0"
    mutable: true
  - name: defaultGw
    attrId: 6
    type: IPv4Addr
    default: "193.254.1.1"
    mutable: true
  - name: mibVersion
    attrId: 7
    type: String
    maxLength: 16
    default: "V2.04.02.08"
    mutable: true
  - name: health
    attrId: 8
    type: AlarmLevelEnum
    default: None
    mutable: true
  - name: mac
    attrId: 9
    type: MacAddr
    mutable: false
