className: DropProfile
tid: 321
triggers: [constraintAdd, constraintSet]
attributes:
  - name: profileName
    attrId: 0      
    type: String
    maxLength: 19
    default: TAILDROP
    mutable: true
  - name: dropMode
    attrId: 1      
    type: BYTE
    enum:
      tailDrop: 0
      red: 1
      wred: 2
    default: tailDrop
    mutable: true
  - name: greenMinThresh
    attrId: 2
    type: WORD32
    minimum: 0
    maximum: 100
    default: 100
    mutable: true
  - name: greenMaxThresh
    attrId: 3
    type: WORD32
    minimum: 0
    maximum: 100
    default: 100
    mutable: true
  - name: greenDropPercent
    attrId: 4
    type: WORD32
    range: [[0,10],[25],[50],[75],[100]]
    default: 100
    mutable: true
  - name: yellowMinThresh
    attrId: 5
    type: WORD32
    minimum: 0
    maximum: 100
    default: 100
    mutable: true
  - name: yellowMaxThresh
    attrId: 6
    type: WORD32
    minimum: 0
    maximum: 100
    default: 100
    mutable: true
  - name: yellowDropPercent
    attrId: 7
    type: WORD32
    range: [[0,10],[25],[50],[75],[100]]
    default: 100
    mutable: true
  - name: redMinThresh
    attrId: 8
    type: WORD32
    minimum: 0
    maximum: 100
    default: 100
    mutable: true
  - name: redMaxThresh
    attrId: 2
    type: WORD32
    minimum: 0
    maximum: 100
    default: 100
    mutable: true
  - name: redDropPercent
    attrId: 9
    type: WORD32
    range: [[0,10],[25],[50],[75],[100]]
    default: 100
    mutable: true
  - name: usedForTAouPort
    attrId: 10
    type: BYTE
