className: HQOSPortNode_aboutPanel
tid: 316
triggers: [beforeSet, afterSet, constraintSet]
baseClass: HQOSPortNode
attributes:
  - name: PIR
    attrId: 3
    type: WORD32
    minimum: 0
    maximum: 10000000
    default: 0
    mutable: true
children:
  - name: L0
    type: HQOSL0Node_noGen
    id: 1
    count: 8
    autoCreate: {"1":HQOSL0Node_autoGen}
