className: LOGStatus
tid: 246
persistence: None
triggers: [afterGet]
attributes:
  - name: status
    attrId: 0
    type: BYTE
    enum:
      processing: 1
      finished: 2
    default: finished
    mutable: true
  - name: result
    attrId: 1 
    type: WORD32
    default: 0
    mutable: true
