className: PmpLinkEth
tid: 381
triggers: [afterGet]
persistence: None
attributes:
  - name: date
    attrId: 0
    type: Date
    maxLength: 50
    mutable: false
  - name: validFlag
    attrId: 1 
    type : PmpValidFlagEnum
    default: valid
    mutable: false
  - name: maxUtilize
    attrId: 2 
    type : WORD32
    mutable: false
  - name: minUtilize
    attrId: 3 
    type : WORD32
    mutable: false
  - name: avgUtilize
    attrId: 4 
    type : WORD32
    mutable: false
actions:
  customs:
    - name: Clear
      actionId: 1
    - name: ClearRsp
      actionId: 101
