className: PortVlan_Access
baseClass: PortVlan_Details
persistence: None
tid: 263
triggers: [afterAdd, constraintAdd, constraintSet]
attributes:
  - name: vlanTag
    attrId: 0
    type: Range
    default: [[0]]
    maxItems: 4094
    mutable: true
