className: StaticMacIVL
tid: 304
triggers: [constraintAdd]
attributes:
  - name: mac
    attrId: 0
    type: MacAddr
    mutable: true
  - name: vlanId
    attrId: 1
    type: WORD16
    minimum: 1
    maximum: 4094
    default: 1
    mutable: true
reference:
  - name: portId
    type: TrafficPort
    isMulti: false
    under: DependencyPolicy
