className: AcmubModThres
baseClass: ModThres
tid: 241
triggers: [constraintSet, recover, beforeAdd]
attributes:
  - name: modulation
    attrId: 0
    type: Qam4096ModulationEnum
    default: QPSK
    mutable: true
  - name: codingType
    attrId: 1
    type: CodingTypeEnum
    default: normal      
    mutable: true

