className: AcmubWorkmode
baseClass: Workmode
tid: 242
triggers: [constraintSet, afterSet, beforeSet]
attributes:
  - name: bandwidth
    attrId: 0
    type: ETSI112MBandWidthEnum
    default: ETSI_7M
    mutable: true
  - name: modulation
    attrId: 1
    type: Qam4096ModulationEnum
    default: QPSK
    mutable: true
  - name: codingType
    attrId: 2
    type: CodingTypeEnum
    default: normal
    mutable: true















