className: Customer_SToC
tid: 261
triggers: [constraintAdd]
attributes:
  - name: sVlan
    attrId: 0
    type: WORD16
    minimum: 1
    maximum: 4094
    default: 1
    mutable: true
  - name: cVlan
    attrId: 1
    type: WORD16
    minimum: 0
    maximum: 4094
    default: 1
    mutable: true
  - name: sVlanPriority
    attrId: 2
    type: BYTE
    minimum: 0
    maximum: 7
    default: 0
    mutable: true
  - name: unTag
    attrId: 3
    type: StateEnum
    default: disable
    mutable: true
