className: PacketAgeTime
tid: 314
triggers: [beforeSet]
attributes:
  - name: packAgeEnable
    attrId: 0
    type: StateEnum
    default: disable
    mutable: true
  - name: BE
    attrId: 1
    type: WORD32
    minimum: 125
    maximum: 7162
    default: 125
    mutable: true
  - name: AF1
    attrId: 2
    type: WORD32
    minimum: 125
    maximum: 7162
    default: 125
    mutable: true
  - name: AF2
    attrId: 3
    type: WORD32
    minimum: 125
    maximum: 7162
    default: 125
    mutable: true
  - name: AF3
    attrId: 4
    type: WORD32
    minimum: 125
    maximum: 7162
    default: 125
    mutable: true
  - name: AF4
    attrId: 5
    type: WORD32
    minimum: 125
    maximum: 7162
    default: 125
    mutable: true
  - name: EF
    attrId: 6
    type: WORD32
    minimum: 125
    maximum: 7162
    default: 125
    mutable: true
  - name: CS6
    attrId: 7
    type: WORD32
    minimum: 125
    maximum: 7162
    default: 125
    mutable: true
  - name: CS7
    attrId: 8
    type: WORD32
    minimum: 125
    maximum: 7162
    default: 125
    mutable: true
