className: PLA
tid: 554
triggers: [beforeAdd, beforeDel, afterAdd, afterDel, afterSet, recover]
attributes:
  - name: state
    attrId: 0
    type: StateEnum
    default: disable
    mutable: true
  - name: memberNum
    attrId: 1
    type: BYTE
    minimum: 2
    maximum: 8
    mutable: true
  - name: masterPortId
    attrId: 2
    type: String
    minLength: 1
    maxLength: 60
    mutable: true
  - name: masterBoard
    attrId: 3
    type: MasterBoardEnum
    default: master
    mutable: true
reference:
  - name: memberPortId
    type: PhyPort
    isMulti: true
    maxItems: 8
    under: ConstraintPolicyInList
children:
   - name : PLALinkId
     id : 1
     count : 1
     autoCreate: true
   - name : PmpRmon
     id : 2
     count : 1
     autoCreate: true
   - name : PmpWleth
     id : 3
     count : 1
     autoCreate: true
