className: PortVlan_Customer
baseClass: PortVlan_Details
tid: 267
triggers: [afterAdd, constraintAdd, constraintSet,afterSet]
attributes:
  - name: inActiveFlag
    attrId: 0
    type: Range
    default: [[0]]
    maxItems: 4094
    mutable: true
  - name: macVlan
    attrId: 1
    type: StateEnum
    default: disable
    mutable: true
  - name: reMap
    attrId: 2
    type: StateEnum
    default: disable
    mutable: true
  - name: TPID
    attrId: 3
    type: WORD32
    enum:
      8100: 33024
      88a8: 34984
      9100: 37120
      9200: 37376
    default: 88a8
    mutable: true
reference:
  - name: protocolVlan
    type: ProtocolVlan
    isMulti: true
    under: ConstraintPolicy
children:
  - name: CToS
    type: Customer_CToS
    id: 1
    count: 8
    autoCreate: false
  - name: SToC
    type: Customer_SToC
    id: 2
    count: 8
    autoCreate: false
