module: address-server
dependency:
  - mosjava
script: |
  export MOS_JAVA_OUTPUT=$(pwd)
  mvn -q clean package -DoutputPath=$MOS_JAVA_OUTPUT -Dlibpath=$MOS_JAVA_OUTPUT -f $CURRENT_DIR
  chmod -R +x ${MOS_JAVA_OUTPUT}
  mkdir ${MOS_JAVA_OUTPUT}/log
  cp $CURRENT_DIR/mos.keystore ${MOS_JAVA_OUTPUT}
