className: ImSyncConfig
baseClass: SyncConfig
tid: 333
persistence: None
override_attributes:
  - name: modelType
    attrId: 3
    type: String
    default: MW_IM_Module
    maxLength: 64
    mutable: true
  - name: interval
    attrId: 4
    type: WORD32
    default: 1440
    mutable: true


