className: NR8120FmSyncConfig
baseClass: FmSyncConfig
tid: 333
persistence: None
override_attributes:
  - name: neType
    attrId: 2
    type: String
    default: mw.nr8120
    maxLength: 64
    mutable: true
  - name: pollTaskName
    attrId: 5
    type: String
    maxLength: 128
    default: ZXMW 8120
    mutable: false

