className: NR8960ImSyncConfig
baseClass: ImSyncConfig
tid: 1
override_attributes:
  - name: neType
    attrId: 2
    type: String
    default: mw.nr8960
    maxLength: 64
    mutable: true
  - name: pollTaskName
    attrId: 5
    type: String
    maxLength: 128
    default: ZXMW 8960
    mutable: false
