className: NR8950ImSyncConfig
baseClass: ImSyncConfig
tid: 1
override_attributes:
  - name: neType
    attrId: 2
    type: String
    default: mw.nr8950
    maxLength: 64
    mutable: true
  - name: pollTaskName
    attrId: 5
    type: String
    maxLength: 128
    default: ZXMW 8950
    mutable: false
