className: RcmuaCuTrafficUnit
baseClass: TrafficUnit
tid: 486
triggers: [afterAdd, afterSet, afterDel, recover]
children:
   - name : EthPort
     type : PhyPort
     id : 1
     count : 7
     groupType : map
     autoCreate: {"E-1": [EthPort_E_1G_NMS, {displayName: "NMS"}], "EIN-1": [EdiInPort, {displayName: "EDIin"}], "EOUT-1": [EdiOutPort, {displayName: "EDIout"}], "CLK-1": [ClkInPort, {displayName: "CLKIN/MON0"}], "CLK-2": [ClkOutPort, {displayName: "CLKOUT/MON1"}], "SC-1": [Sc28Port, {displayName: "SC1"}], "SC-2": [Sc11Port, {displayName: "SC2"}]}
