className: AirPort
tid: 502
triggers: [afterAdd,afterGet]
persistence: None
attributes:
  - name: logicAirPortNo
    attrId: 0 
    type : BYTE
    mutable: true
  - name: xpdValue
    attrId: 1
    type: BYTE
    default: 255
    mutable: true
  - name: lockStatus
    attrId: 2
    type: BYTE
    enum:
      lock: 1
      unlock: 0 
    default: unlock
    mutable: true
  - name: xpicStatus
    attrId: 3
    type: StateEnum
    default: disable
    mutable: true
children:
   - name : OduAttribute
     id : 1
     count : 1
     autoCreate: true
   - name : RfStatus
     id : 2
     count : 1
     autoCreate: true
   - name : ModemStatus
     id : 3 
     count : 1
     autoCreate: true
   - name : PmpAcm
     id : 4 
     count : 1
     autoCreate: true
   - name : PmpRf
     id : 5
     count : 1
     autoCreate: true
   - name : PmpWleth
     id : 6
     count : 1
     autoCreate: true
   - name : PmpXpic
     id : 7 
     count : 1
     autoCreate: true
   - name : PmpRadioLink
     id : 8
     count : 1
     autoCreate: true
   - name : PmpThresh
     id : 9
     count : 1
     autoCreate: true
   - name : FadeMarginInfo
     id : 10
     count : 1
     autoCreate: true
   - name : PmpRmon
     id : 11
     count : 1
     autoCreate: true
   - name : PmpE1Radio
     id : 12
     count : 1
     autoCreate: true
   - name : OduVersion
     id : 13
     count : 1
     autoCreate: true
actions:
  customs:
    - name: RfLoopback
      actionId: 1
      attributes:
        - name: state
          attrId: 0  
          type: StateEnum
          default: disable
          mutable: true
        - name: time
          attrId: 1 
          type: WORD32
          default: 10
          mutable: true
    - name: ModemTone
      actionId: 2
      attributes:
        - name: state
          attrId: 0  
          type: StateEnum
          default: disable
          mutable: true
        - name: time
          attrId: 1 
          type: WORD32
          default: 10
          mutable: true
    - name: RfMute
      actionId: 3
      attributes:
        - name: state
          attrId: 0  
          type: StateEnum
          default: disable
          mutable: true
        - name: time
          attrId: 1 
          type: WORD32
          default: 10
          mutable: true
    - name: RfLoopbackRsp
      actionId: 101
    - name: ModemToneRsp
      actionId: 102
    - name: RfMuteRsp
      actionId: 103
 
        
