className: Rpu
baseClass: Board
tid: 471
triggers: [afterGet]
attributes:
  - name: boardType
    attrId: 0
    type: BoardTypeEnum
    default: rpua
    mutable: false
  - name: ps1status
    attrId: 1
    type: BYTE
    default: 0
    mutable: true
  - name: ps2status
    attrId: 2
    type: BYTE
    default: 0
    mutable: true