className: MucModThres
baseClass: ModThres
tid: 592
triggers: [constraintSet, recover, beforeAdd]
attributes:
  - name: modulation
    attrId: 0
    type: Qam256ModulationEnum
    default: QPSK
    mutable: true
  - name: codingType
    attrId: 1
    type: CodingTypeEnum
    default: normal      
    mutable: true
