className: MueAcm
baseClass: Acm
triggers: [constraintSet, afterSet, afterGet]
tid: 531
attributes: 
  - name: startModulation
    attrId: 0
    type: Qam256ModulationEnum
    default: QPSK
    mutable: true
  - name: endModulation
    attrId: 1
    type: Qam256ModulationEnum
    default: QPSK
    mutable: true
  - name: startCodingType
    attrId: 2
    type: CodingTypeEnum
    default: normal
    mutable: false
  - name: endCodingType
    attrId: 3
    type: CodingTypeEnum
    default: normal
    mutable: false
















