className: MueModemCfgType
baseClass: ModemCfgType
tid: 535
triggers: [recover, afterAdd]
attributes:
  - name: cfgType
    attrId: 0
    type: BYTE
    enum:
      typical: 0
    default: typical
    mutable: false
