className: RtuioTrafficUnit
baseClass: TrafficUnit
tid: 451
triggers: [afterAdd, afterSet, afterDel, recover]
children:
   - name : EthPort
     type : PhyPort
     id : 1
     count : 1
     groupType : map
     autoCreate: {"O-1": [EthPort_O_10G, {displayName: "GbE1"}]}
