className: Stm1OverHead
tid: 154
persistence: Update
triggers: [afterGet]
attributes:
  - name: mode
    attrId: 0
    type: SdhOverHeadModeEnum
    default: automatic
    mutable: true
  - name: J0Received
    attrId: 1
    type: String
    maxLength: 16
    default: ""
    mutable: true
  - name: J0Transmitted
    attrId: 2
    type: String
    maxLength: 16
    default: ""
    mutable: true
  - name: J0Expected
    attrId: 3
    type: String
    maxLength: 16
    default: ""
    mutable: true
  - name: J0StringLength
    attrId: 4
    type: BYTE
    mutable: true
  - name: J1ReceivedTrace
    attrId: 5
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1TransmittedTrace
    attrId: 6
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1ExpectedTrace
    attrId: 7
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1StringLength
    attrId: 8
    type: BYTE
    mutable: true
  - name: C2ReceivedTrace
    attrId: 9
    type: BYTE
    mutable: true
  - name: C2TransmittedTrace
    attrId: 10
    type: BYTE
    mutable: true
  - name: C2ExpectedTrace
    attrId: 11
    type: BYTE
    mutable: true
  - name: C2StringLength
    attrId: 12
    type: BYTE
    mutable: true
    
