className: Stm4OverHead
tid: 155
persistence: Update
triggers: [afterGet]
attributes:
  - name: mode
    attrId: 0
    type: SdhOverHeadModeEnum
    default: automatic
    mutable: true
  - name: J0Received
    attrId: 1
    type: String
    maxLength: 16
    default: ""
    mutable: true
  - name: J0Transmitted
    attrId: 2
    type: String
    maxLength: 16
    default: ""
    mutable: true
  - name: J0Expected
    attrId: 3
    type: String
    maxLength: 16
    default: ""
    mutable: true
  - name: J0StringLength
    attrId: 4
    type: BYTE
    mutable: true
  - name: J1Path1ReceivedTrace
    attrId: 5
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1Path2ReceivedTrace
    attrId: 6
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1Path3ReceivedTrace
    attrId: 7
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1Path4ReceivedTrace
    attrId: 8
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1Path1TransmittedTrace
    attrId: 9
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1Path2TransmittedTrace
    attrId: 10
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1Path3TransmittedTrace
    attrId: 11
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1Path4TransmittedTrace
    attrId: 12
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1Path1ExpectedTrace
    attrId: 13
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1Path2ExpectedTrace
    attrId: 14
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1Path3ExpectedTrace
    attrId: 15
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1Path4ExpectedTrace
    attrId: 16
    type: String
    maxLength: 64
    default: ""
    mutable: true
  - name: J1StringLength
    attrId: 17
    type: Array
    maxItems: 4
    items:
      type: BYTE
    mutable: true
  - name: C2ReceivedTrace
    attrId: 18
    type: Array
    maxItems: 4
    items:
      type: BYTE
    mutable: true
  - name: C2TransmittedTrace
    attrId: 19
    type: Array
    maxItems: 4
    items:
      type: BYTE
    mutable: true
  - name: C2ExpectedTrace
    attrId: 20
    type: Array
    maxItems: 4
    items:
      type: BYTE
    mutable: true
  - name: C2StringLength
    attrId: 21
    type: Array
    maxItems: 4
    items:
      type: BYTE
    mutable: true

    
