module: moslite
dependency:
  - mosjava
script: |
  export MOS_JAVA_OUTPUT=$(pwd)
  mvn -q clean package -Dmaven.test.skip=true -DoutputPath=$MOS_JAVA_OUTPUT -Dlibpath=$MOS_JAVA_OUTPUT -f $CURRENT_DIR
  chmod -R +x ${MOS_JAVA_OUTPUT}
  mkdir ${MOS_JAVA_OUTPUT}/log
  mkdir ${MOS_JAVA_OUTPUT}/store
