package com.zte.scope.common;

public class EmsModelMib
{
    public static final String[] mibs = {"/Ems"
            , "/Ems/CesService"
            , "/Ems/PhysicalLink"
            , "/Ems/IpV4"
            , "/Ems/VersionModule"
            , "/Ems/CmModule"
            , "/Ems/GroupNode"
            , "/Ems/LogicalNode"
            , "/Ems/LogicalLink"
            , "/Ems/GroupLink"
            , "/Ems/SyncConfig"
            , "/Ems/LogicalNode"
            , "/Ems/LogicalNode/ports"
            , "/Ems/LogicalNode/ports/CToS"
            , "/Ems/LogicalNode/ports/portsBlockedVlan"
            , "/Ems/LogicalLink"
            , "/Ems/GroupLink"
            , "/Ems/Tunnel"
            , "/Ems/ClockLink"
            , "/Ems/ClockGroupLink"
            , "/Ems/QinQ"
            , "/Ems/EVC"
            , "/Ems/EVC/unis"
            , "/Ems/EVC/unis/CToS"
            , "/Ems/EVC/oamPara"
            , "/Ems/QinQMangement"
            , "/Ems/VersionModule/TaskGroup"
            , "/Ems/VersionModule/UnifiedVersionPackage"
            , "/Ems/VersionModule/TaskGroup/Task"
            , "/Ems/VersionModule/TaskGroup/Task/SubTask"
            , "/Ems/VersionModule/UnifiedVersionPackage/SoftwarePackage"
            , "/Ems/VersionModule/UnifiedVersionPackage/FirmwarePackage"
            , "/Ems/VersionModule/UnifiedVersionPackage/FirmwarePackage/VersionPackage"
            , "/Ems/VersionModule/UnifiedVersionPackage/SoftwarePackage/VersionPackage"
            , "/Ems/SwitchTransNode"
            , "/Ems/MplsTransNode"
            , "/Ems/SwitchTransNode/EthPort"
            , "/Ems/MplsTransNode/EthPort"
            , "/Ems/EmsNode"
            , "/Ems/EmsNode/EthPort"
            , "/Ems/TopoModule"
            , "/Ems/InventoryModule"
            , "/Ems/NeinModule"
            , "/Ems/BatchTaskModule"
            , "/Ems/BatchTaskModule/CmTaskGroup"
            , "/Ems/BatchTaskModule/CmTaskGroup/CmSubTask",
            "/Ems/SiteReportModule",
            "/Ems/SiteReportModule/SiteReportSuperTask",
            "/Ems/SiteReportModule/SiteReportSuperTask/SiteReportSubTask",
            "/Ems/SiteReportModule/SiteReportSuperTask/SiteReportTaskPara",
            "/Ems/LLDPLogicalLink"
            , "/Ems/DSDomain"
            , "/Ems/DSDomain/DropProfilePara"
            , "/Ems/DSDomain/HQosPortPara"
            , "/Ems/DSDomain/HQosPortPara/HQosL0Para"
            , "/Ems/DSDomain/HQosPortPara/HQosL0Para/HQosL1Para"
            , "/Ems/DSDomain/HQosPortPara/HQosL0Para/HQosL1Para/HQosL2Para"
    };
}
