className: PDHRTBL
tid: 107
triggers: [afterGet]
attributes:
  - name: ucRackNo
    attrId: 0
    type: WORD32
    default: 0
    mutable: true
  - name: ucSourceShelfNo
    attrId: 1
    type: WORD32
    default: 0
    mutable: true
  - name: ucSourceUnitNo
    attrId: 2
    type: WORD32
    default: 0
    mutable: true
  - name: dwSourcePortID
    attrId: 3
    type: WORD32
    default: 0
    mutable: true
  - name: ucSourceVC4
    attrId: 4
    type: WORD32
    default: 0
    mutable: true
  - name: ucSourceIndex
    attrId: 5
    type: WORD32
    default: 0
    mutable: true
  - name: ucDestShelfNo
    attrId: 6
    type: WORD32
    default: 0
    mutable: true
  - name: ucDestUnitNo
    attrId: 7
    type: WORD32
    default: 0
    mutable: true
  - name: dwDestPortID
    attrId: 8
    type: WORD32
    default: 0
    mutable: true
  - name: ucDestVC4
    attrId: 9
    type: WORD32
    default: 0
    mutable: true
  - name: ucDestIndex
    attrId: 10
    type: WORD32
    default: 0
    mutable: true
  - name: ucDirection
    attrId: 11
    type: WORD32
    default: 0
    mutable: true
  - name: ucActiveFlag
    attrId: 12
    type: WORD32
    default: 0
    mutable: true
    