className: TTMSOURCE
tid: 107
triggers: [afterGet]
attributes:
  - name: MUREALNUM
    attrId: 0
    type: WORD32
    default: 0
    mutable: true
  - name: TUREALNUM
    attrId: 1
    type: WORD32
    default: 0
    mutable: true
  - name: MUORTU
    attrId: 2
    type: WORD32
    default: 0
    mutable: true
  - name: UCTRAFFICUNITNO
    attrId: 3
    type: WORD32
    default: 0
    mutable: true
  - name: ACCOUNTRMU
    attrId: 4
    type: String
    maxLength : 1000
    mutable: true
  - name: ACCOUNTRTU
    attrId: 5
    type: String
    maxLength : 1000
    mutable: true
    
