className: RcmucModThres
baseClass: ModThres
tid: 144
triggers: [constraintSet, recover, beforeAdd]
attributes:
  - name: modulation
    attrId: 0
    type: Qam2048ModulationEnum
    default: QPSK
    mutable: true
  - name: codingType
    attrId: 1
    type: CodingTypeEnum
    default: normal      
    mutable: true
