className: RcmucTuTrafficUnit
baseClass: TrafficUnit
tid: 473
triggers: [afterAdd, afterSet, afterDel, recover]
children:
   - name : EthPort
     type : PhyPort
     id : 1
     count : 4
     groupType : map
     autoCreate: {"O-1": [EthPort_O_10G, {displayName: "GbE5/10GbE"}], "O-2": [EthPort_O_1G, {displayName: "GbE6"}], "O-3": [EthPort_O_1G_Prot, {displayName: "PROT"}], "O-4": [EthPort_O_1G_Pla, {displayName: "PLA"}]}
