className: RmeaWorkmode
baseClass: Workmode
tid: 590
triggers: [constraintSet, afterSet, beforeSet]
attributes:
  - name: bandwidth
    attrId: 0
    type: ETSIBandWidthEnum
    default: ETSI_7M
    mutable: true
  - name: modulation
    attrId: 1
    type: Qam256ModulationEnum
    default: QPSK
    mutable: true
  - name: codingType
    attrId: 2
    type: CodingTypeEnum
    default: normal
    mutable: false














